services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-server
      
  Backend-Flask:
    image: anasaljaour1/backend-flask:latest
    build: ./BackEnd-Flask  
    

  Backend-Node:
    image: anasaljaour1/backend-node:latest
    build: ./BackEnd
    depends_on:
      - Backend-Flask

  frontend-server:
    image: anasaljaour1/frontend:latest
    build: ./FrontEnd
    ports:
      - "8501:8501"
    depends_on:
      - Backend-Node
