name: Deploy to Production

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      
      - name: Build & Push Backend-Node
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-node:latest ./app/BackEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-node:latest

      
      - name: Build & Push Backend-Flask
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-flask:latest ./app/BackEnd-Flask
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-flask:latest

      
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./app/FrontEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add GCP VM to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/known_hosts

      - name: SSH to GCP and deploy
        run: |
          ssh ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }} << 'EOF'
            cd ~/AIDE505-FinalProject/app  # Navigate to the app folder where docker-compose.prod.yml is located
            git pull origin main  # Make sure we have the latest code
            docker-compose -f docker-compose.prod.yml up -d  # Run docker-compose to start the services
          EOF

